"""
MEDICA Markdown Knowledge Store
Reads and writes structured markdown files to the knowledge filesystem.
The filesystem is the canonical knowledge layer.
"""
from __future__ import annotations

from datetime import datetime
from pathlib import Path

from core.config import settings
from core.logging import get_logger
from core.types import PaperMetadata
from shared.utils import render_markdown, safe_write, slugify, truncate

logger = get_logger(__name__)

# Markdown template for a paper
_PAPER_TEMPLATE = """## Abstract

{abstract}

## Methodology

*To be extracted by the processing pipeline.*

## Key Findings

*To be summarized by the AI agent.*

## Limitations

*To be identified by the adversarial verification agent.*

## Extracted Claims

*Claims will be populated during verification.*

## Treatment Relevance

{treatment_relevance}

## Biomarker Relevance

{biomarker_relevance}

## Toxicity Notes

*No toxicity data extracted yet.*

## AI Summary

*Summary will be generated by the research agent.*

## Adversarial Review

{adversarial_review}

## Citations

{citations}
"""


class KnowledgeStore:
    """
    Markdown filesystem knowledge store.

    Organizes papers under:
      knowledge/
        cancers/<cancer_type>/papers/<pmid_or_doi>.md
        entities/drugs/<drug_name>.md
        entities/biomarkers/<biomarker>.md

    Each paper is stored as structured markdown with YAML frontmatter.
    """

    def __init__(self, base_path: Path | None = None) -> None:
        self.base = base_path or settings.knowledge_base_path
        self.base = Path(self.base)

    def _paper_path(self, paper: PaperMetadata) -> Path:
        """Determine the filesystem path for a paper."""
        # Route by primary cancer type, or 'general' if none
        cancer_tags = paper.tags.cancer if paper.tags else []
        primary_cancer = cancer_tags[0] if cancer_tags else "general"

        # Use PMID, DOI slug, or title slug as filename
        if paper.pmid:
            filename = f"pmid_{paper.pmid}.md"
        elif paper.doi:
            filename = f"doi_{slugify(paper.doi)}.md"
        else:
            filename = f"{slugify(paper.title[:60])}.md"

        return self.base / "cancers" / primary_cancer / "papers" / filename

    def _build_frontmatter(self, paper: PaperMetadata) -> dict:
        """Build YAML frontmatter dict from paper metadata."""
        return {
            "id": str(paper.id),
            "title": paper.title,
            "pmid": paper.pmid,
            "doi": paper.doi,
            "journal": paper.journal,
            "published": paper.published.isoformat() if paper.published else None,
            "published_precision": paper.published_precision,
            "authors": paper.authors[:10],  # Cap at 10
            "source": paper.source.value,
            "verification_status": paper.verification_status.value,
            "confidence_score": paper.confidence_score,
            "evidence_level": paper.evidence_level.value,
            "study_type": paper.study_type.value,
            "trial_phase": paper.trial_phase.value if paper.trial_phase else None,
            "tags": {
                "cancer": paper.tags.cancer,
                "treatment": paper.tags.treatment,
                "biomarkers": paper.tags.biomarkers,
                "drugs": paper.tags.drugs,
                "evidence": paper.tags.evidence,
                "outcomes": paper.tags.outcomes,
                "study_type": paper.tags.study_type,
                "temporal": paper.tags.temporal,
                "system": paper.tags.system,
            },
            "linked_entities": paper.linked_entities[:20],
            "related_papers": paper.related_papers[:10],
            "contradictory_papers": paper.contradictory_papers[:10],
            "citation_count": paper.citation_count,
            "ingested_at": datetime.utcnow().isoformat(),
            "updated_at": datetime.utcnow().isoformat(),
        }

    def _build_body(self, paper: PaperMetadata, adversarial_review: str | None = None) -> str:
        """Build markdown body for a paper."""
        # Treatment relevance from tags
        if paper.tags.treatment:
            treatment_relevance = ", ".join(f"`{t}`" for t in paper.tags.treatment)
        else:
            treatment_relevance = "*No treatment tags identified.*"

        # Biomarker relevance from tags
        if paper.tags.biomarkers:
            biomarker_relevance = ", ".join(f"`{b}`" for b in paper.tags.biomarkers)
        else:
            biomarker_relevance = "*No biomarker tags identified.*"

        # Citations
        citations = ""
        if paper.doi:
            citations += f"- DOI: https://doi.org/{paper.doi}\n"
        if paper.pmid:
            citations += f"- PubMed: https://pubmed.ncbi.nlm.nih.gov/{paper.pmid}/\n"
        if not citations:
            citations = "*No citation links available.*"

        return _PAPER_TEMPLATE.format(
            abstract=paper.abstract or "*No abstract available.*",
            treatment_relevance=treatment_relevance,
            biomarker_relevance=biomarker_relevance,
            adversarial_review=adversarial_review or "*Adversarial review pending.*",
            citations=citations,
        )

    async def store(
        self,
        paper: PaperMetadata,
        adversarial_review: str | None = None,
    ) -> Path:
        """
        Store a paper as a structured markdown file.

        Returns the path where the file was written.
        """
        path = self._paper_path(paper)
        frontmatter = self._build_frontmatter(paper)
        body = self._build_body(paper, adversarial_review)
        content = render_markdown(frontmatter, body)
        safe_write(path, content)

        logger.info(
            "knowledge_stored",
            path=str(path),
            pmid=paper.pmid,
            title=truncate(paper.title, 60),
        )

        return path

    async def read(self, path: Path) -> tuple[dict, str] | None:
        """Read a markdown knowledge file. Returns (frontmatter, body) or None."""
        from shared.utils import parse_markdown, safe_read
        content = safe_read(path)
        if content is None:
            return None
        return parse_markdown(content)

    async def update_frontmatter(self, path: Path, updates: dict) -> bool:
        """Update specific frontmatter fields in a knowledge file."""
        from shared.utils import parse_markdown, render_markdown, safe_read
        content = safe_read(path)
        if content is None:
            return False
        frontmatter, body = parse_markdown(content)
        frontmatter.update(updates)
        frontmatter["updated_at"] = datetime.utcnow().isoformat()
        safe_write(path, render_markdown(frontmatter, body))
        return True

    def list_papers(self, cancer_type: str | None = None) -> list[Path]:
        """List all paper markdown files, optionally filtered by cancer type."""
        if cancer_type:
            search_root = self.base / "cancers" / cancer_type / "papers"
        else:
            search_root = self.base / "cancers"

        if not search_root.exists():
            return []

        return list(search_root.rglob("*.md"))

    def list_cancer_types(self) -> list[str]:
        """List all cancer type directories."""
        cancers_dir = self.base / "cancers"
        if not cancers_dir.exists():
            return []
        return [d.name for d in cancers_dir.iterdir() if d.is_dir()]
